### ISSUE TITLE
catch ctrl+p

### ISSUE THREAD

**Issue by Julime** [Julime/SubConf#12]
and use the print function

**Comment by MarcelBulpr** [comment]
done

**Comment by MarcelBulpr** [comment]
I also changed all redirects so they read the url and don´t depend on a set value

**Comment by Julime** [comment]
CTRL+P: `The requested URL /helper/print.php was not found on this server.`
CMD+P: mac default print

**Comment by MarcelBulpr** [comment]
I prevented the default action on strg+P wich firefox had Problems with but i couldn´t test it on Mac

**Comment by MarcelBulpr** [comment]
done
