### ISSUE TITLE
Display menu of the day

### ISSUE THREAD

**Issue by Julime** [Julime/SubConf#2]
Display menu of the day at the meat selection

![5cde404c ngrok io_2016-01-13_10-25-25](https://cloud.githubusercontent.com/assets/7944656/12290097/08813d58-b9e0-11e5-981f-dd36a15fa5fe.png)

**Comment by MarcelBulpr** [comment]
Sub of the day doesn't exist anymore it got replaced by menu of the day

**Comment by MarcelBulpr** [comment]
done
